#!/bin/bash
What is kernal.?
--> kernal is program which is allow to interpet/comunication beetween software and hardware.
================================================================================list of some kernal.
2)linux 
2)windows NT
3)fressbsd kernal
4)GNU Hurd
================================================================================Androied usege a Linux kernal.
===============================================================================
