#!/bin/bash
read -p "Enter Number :- " num
i=2
f=0
while [ $i -le `expr $num /2` ]
do 
if [ `expr $num % $i` -eq 0 ]
then 
f=1
fi 
i=`expr $i + 1`
done
if [ $f -eq 1 ]
then 
echo " then number is composite "
else 
echo "The number is prime "
fi
