#!/bin/bash
What is shell scripting.?
--> set of linux and unix commnds.  Which program is interpat between user and kernal its called  shell scripting.

How different  from other programming languages.?
--->
